### PR TITLE
Fixing tint UIImage extension upside down.

### LINKED ISSUE #586: UIImage: Tinted image results in flipped image
[x] I've read, understood, and done my best to follow the [Contributing guidelines](https://github.com/SwifterSwift/SwifterSwift/tree/master/CONTRIBUTING.md) before opening this issue.

### What did you do?
Tinted image
```
backgroundImage.image = UIImage(named: "image")?.tint(UIColor.black, blendMode: .normal)
```

### What did you expect to happen?
Image with tinted color

### What happened instead?
Image with tinted color that is vertically flipped

### SwifterSwift Environment

- SwifterSwift version: 4.5.0
- Xcode version: Version 10.0 (10A255)
- macOS version running Xcode:
- Swift version:
- Platform(s) running SwifterSwift:

### Demo Project
-

### PR DESCRIPTION
**Pull request by LucianoPAlmeida**
Fixes #586
## Checklist

- [x] I checked the [**Contributing Guidelines**](https://github.com/SwifterSwift/SwifterSwift/blob/master/CONTRIBUTING.md) before creating this request.
- [x] New extensions are written in Swift 4.
- [x] New extensions support iOS 8.0+ / tvOS 9.0+ / macOS 10.10+ / watchOS 2.0+.
- [x] I have added tests for new extensions, and they passed.
- [x] All extensions have a **clear** comments explaining their functionality, all parameters and return type in English.
- [x] All extensions are declared as **public**.
- [x] I have added a [changelog](https://github.com/SwifterSwift/SwifterSwift/blob/master/CHANGELOG_GUIDELINES.md) entry describing my changes.

### CODE REVIEW

File: Sources/Extensions/UIKit/UIImageExtensions.swift [hunk 1]
```diff
@@ -189,16 +189,16 @@ public extension UIImage {
     ///   - blendMode: how to blend the tint
     /// - Returns: UIImage tinted with given color.
     public func tint(_ color: UIColor, blendMode: CGBlendMode) -> UIImage {
-        let drawRect = CGRect(x: 0.0, y: 0.0, width: size.width, height: size.height)
+        let drawRect = CGRect(origin: .zero, size: CGSize(width: size.width, height: size.height))
```
Comment (guykogus) [inline Sources/Extensions/UIKit/UIImageExtensions.swift]:
```suggestion
        let drawRect = CGRect(origin: .zero, size: size)
```

File: Sources/Extensions/UIKit/UIImageExtensions.swift [hunk 2]
```diff
@@ -189,16 +189,16 @@ public extension UIImage {
...
         UIGraphicsBeginImageContextWithOptions(size, false, scale)
+        defer {
+            UIGraphicsEndImageContext()
```
Comment (guykogus) [inline Sources/Extensions/UIKit/UIImageExtensions.swift]: Why `defer` instead of using the original method? There's nowhere that this function is being exited early.

Comment (LucianoPAlmeida) [reply Sources/Extensions/UIKit/UIImageExtensions.swift]: Is just to avoid the have to store the variable to end the context and then return it. Just return the value and end the context on defer.

**Comment by guykogus** [comment]
@LucianoPAlmeida I'll leave it for you to merge whenever you're comfortable to do so.

**Comment by LucianoPAlmeida** [comment]
I think it is good to go. Was just waiting for the at least one of the others review :)) 
cc @omaralbeik @SD10 @BennX
