### PR TITLE
Fix React-Native conflict issue

### LINKED ISSUE #383: Conflict between SwifterSwift and React-Native
[ x] I've read, understood, and done my best to follow the [Contributing guidelines](https://github.com/SwifterSwift/SwifterSwift/tree/master/CONTRIBUTING.md) before opening this issue.

### What did you do?
I have a React-Native based project, and I use SwifterSwift in the native part.

### What did you expect to happen?
Everything will be OK.

### What happened instead?
Got a crash when I set text component borderColor in JS part.
I think there is some conflict between SwifterSwift and React-Native. 

default
default
default

### SwifterSwift Environment

- SwifterSwift version: 4.1.1
- Xcode version: 9.2
- macOS version running Xcode: 10.13.3
- Swift version: 4.0
- Platform(s) running SwifterSwift: iOS

### Demo Project
https://github.com/syq7970/RNSwifterSwiftBugDemo

### PR DESCRIPTION
**Pull request by syq7970**
Fix #383 , please check this.

### CODE REVIEW

File: Sources/Extensions/UIKit/UIViewExtensions.swift [hunk 1]
```diff
@@ -56,6 +56,10 @@ public extension UIView {
 				layer.borderColor = nil
 				return
 			}
+            // Fix React-Native conflict issue
+            if String(describing: type(of: newValue!)) == "__NSCFType" {
```
Comment (omaralbeik) [inline Sources/Extensions/UIKit/UIViewExtensions.swift]: Could you update the code to avoid force unwrapping:

```swift
guard String(describing: type(of: color)) != "__NSCFType" else { return }
```

**Comment by syq7970** [comment]
@omaralbeik updated

**Comment by SD10** [comment]
Thank you for contributing to SwifterSwift! I've invited you to join the SwifterSwift GitHub organization - no pressure to accept! If you'd like more information on what that means, check out our [contributing guidelines](https://github.com/SwifterSwift/SwifterSwift/blob/master/CONTRIBUTING.md). Feel free to reach out if you have any questions! 😃

**Comment by omaralbeik** [comment]
Thank you @syq7970 👍
